### ISSUE TITLE
Setting number.tessy_charge_current complains about number.tessy_charge_limit is outside valid

### ISSUE THREAD

**Issue by Johanbos** [Teslemetry/hass-teslemetry#109]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When setting a valid value for **tessy_charge_current** an error shows about the **tessy_charge_limit** range.

The logical range for tessy_charge_current should be 5 - 40?

```
Executed: 4 July 2024 at 12:24:11
Error: Value 10.0 for number.tessy_charge_limit is outside valid range 50 - 100
Result:

params:
  domain: number
  service: set_value
  service_data:
    value: 10
    device_id:
      - f80dc8862628273547d96b1a72cfa424
    entity_id:
      - number.tessy_charge_current
  target:
    device_id:
      - f80dc8862628273547d96b1a72cfa424
    entity_id:
      - number.tessy_charge_current
running_script: false
```

### Reproduction steps

1. Install Integration and supply accesstoken
2. Leave everything default!
3. Create automation setting tessy_charge_current
4. Error is shown instead of setting the value
...

**Comment by Johanbos** [comment]
Hmm, https://github.com/Teslemetry/hass-teslemetry/blob/main/custom_components/teslemetry/number.py & https://github.com/home-assistant/core/blob/dev/homeassistant/components/teslemetry/number.py seem to have the proper values.

**Comment by Bre77** [comment]
The issue is your setting the device_id and entity_id so you end up calling set_value on `tessy_charge_limit` instead.

Please only specify the entity_id and *not* the device_id
