### ISSUE TITLE
Home Link

### ISSUE THREAD

**Issue by ddaddy** [Teslemetry/hass-teslemetry#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Can you add support for activating Home Link please?

### Describe the solution you'd like

Home Link activation

### Describe alternatives you've considered

None

### Additional context

Nothing

**Comment by ddaddy** [comment]
No problem

**Comment by Bre77** [comment]
The latest release has Home Link button and it works as far as I can test it. Let me know what error you get when running it.

**Comment by Bre77** [comment]
Sorry I should have been cleared you'll need to update to the latest release, which in HACS may require you to tick the beta switch to see it.

**Comment by ddaddy** [comment]
Ah ok. I did update but not to the beta. I’ll get back to you.

**Comment by ddaddy** [comment]
```
2024-02-13 08:58:18.805 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Teslemetry for teslemetry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/__init__.py", line 78, in async_setup_entry
    car_type=product["vehicle_config"]["car_type"],
             ~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'vehicle_config'
```

**Comment by Bre77** [comment]
Ok leave it with me.

**Comment by Bre77** [comment]
Turns out this was a change made by Tesla to the product API endpoint, took out the whole integration. A new version has been released to fix it.

**Comment by Bre77** [comment]
@ddaddy please retest with the latest version (1.5.5) when possible.
