### ISSUE TITLE
Polling interval / Sleep

### ISSUE THREAD

**Issue by ddaddy** [Teslemetry/hass-teslemetry#13]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Can we get some information on how this polls the car and how it might affect the car sleeping?
In fact, maybe you could add the cars Sleep status too?

### Describe the solution you'd like

I'd like to see my car sleep which it hasn't done for a while using a previous HA integration.

### Describe alternatives you've considered

Other HA projects

### Additional context

None

**Comment by Bre77** [comment]
There is a binary sensor called status which shows if the vehicle is connected or not. Modern vehicles with up to date firmware will fall asleep even when being polled.

I don't currently have a solution for older Model S and X vehicles.

Polling will eventually be replaced partially with Fleet Telemetry, but this also doesn't support older Model S and X vehicles.

**Comment by ddaddy** [comment]
Ah ok. I have a 2017 Model S still with MCU1 so it's latest firmware is 2022.8.10.16

**Comment by Bre77** [comment]
Ok then Teslemetry in Home Assistant may be keeping your vehicle awake in its current state. Check the state binary sensor.

The Tessie integration would work in the meantime as it does have server-side logic to let your vehicle sleep.

**Comment by ddaddy** [comment]
Is it possible to disable polling and have a button to refresh as and when?

**Comment by Bre77** [comment]
Yes, you can do this natively in Home Assistant already.

Go to the config entry, click the three dots, System Options, disable polling.

Then great an automation to call the homeassistant.update_entity on any of the Teslemetry vehicle entities at whatever interval and schedule you want.

**Comment by ddaddy** [comment]
Excellent.
I've just noticed that all the sensors are showing `Unavailable` except for the `Status` one which shows `Connected`.

Clicking `Test API` on your web dashboard works, but `Test Stream` gives a Bad Gateway, could that be connected?

**Comment by Bre77** [comment]
I just fixed a server side issue that happened to cause an integration side issue, if you update to the latest version as of an hour, it should be resolved. I provide real-time updates on Discord.

https://discord.gg/7wZwHaZbWD

**Comment by ddaddy** [comment]
Perfect, working again. I only installed a couple of hours ago so just missed your update.
