### ISSUE TITLE
HA integration no longer loads

### ISSUE THREAD

**Issue by jds11111** [Teslemetry/hass-teslemetry#132]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Today I had problems with making a service call to the car using teslemetry. It showed a short-lived notification on the integration page and said to check the logs.

The logs did show an error, given below. i tried a few times, then tried reloading the integration, which failed to load. I restarted HA, but it still failed to load the integration. 

i did recently update the integration, which required a new token, but it worked fine for several days afterwards. This doesn't seem like enough information to find the problem, but would be happy to provide whatever you think would be helpful.

### Reproduction steps

1. Purchase an account.
2. Install the integration.
3. Use it for a few months.
4. Watch the integration fail to load?
...

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 8:35:05 PM (3 occurrences)
Last logged: 8:41:51 PM

Error setting up entry Teslemetry for teslemetry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/__init__.py", line 98, in async_setup_entry
    scopes = calls[0]["scopes"]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'scopes'
```

**Comment by Bre77** [comment]
Yes this is an issue, will fix server-side asap

**Comment by Bre77** [comment]
This should be resolved now, sorry for the inconvenience. Reload the integration or restarat HA to get back up and running.

**Comment by jds11111** [comment]
Nevermind. It appears to have been a general issue with HA, and the Teslemetry integration was just the first symptom. An upgrade in the HA container seems to have fixed things.
