### ISSUE TITLE
Troubleshooting a badly behaved Tesla: Fleet API must move all 4 windows or none?

### ISSUE THREAD

**Issue by fhteagle** [Teslemetry/hass-teslemetry#135]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This is less a "bug report" as a "discussion / request for information", but the discussions tab is not enabled for this repo, so.........

We are having a big problem with uncommanded window movement on a 2023 Model Y LR. At random, a single window will move itself away from fully closed, far more than a "vent" position, with the car parked, locked, and no one in or near the vehicle. I had a Tesla pull logs, they are claiming it is window switch activation by user, which is of course impossible if no one is in the car, it is locked, etc. Trying to rule out Fleet API / Teslemetry based on one simple question: There are only API commands that move all 4 windows to closed or to vent position, but no way for the Fleet API to command a single window to move, correct?

Thanks.

### Reproduction steps

* Skipping this as I highly doubt anyone would be able to reproduce this on their own vehicle *

**Comment by Bre77** [comment]
That is correct, as far as I am aware the Tesla Fleet API can only "vent" which opens all four windows. I believe Tessie is able to control windows individually over **bluetooth** only.

If you email support@teslemetry.com with your VIN and a timerange I can check the logs to see if any Teslemetry commands were run at that time.

**Comment by fhteagle** [comment]
You can probably close this, at least for now. It has only done it once more since my first report, and I got busy so forgot to forward logs about that one event. We'll see if the problem comes back once it warms up here in the northern hemisphere, but I am really hoping one of the many firmware updates that the car has gotten lately fixed it for real.
