### ISSUE TITLE
Could wall connector card display vehicle name

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#20]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently Wall Connector integration shows the VIN of the connected vehicle.

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/585b5933-1a64-4a98-a931-e313c3f5a50d)

### Describe the solution you'd like

Could it also show the vehicle display_name aka Tesla App please?

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/aab1f823-c403-4fce-8772-5fec250ee02b)

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/cb9339d0-fd44-4f20-97de-a81d1db07d4e)

**Comment by Bre77** [comment]
Its an interesting idea that is technically possible but rather difficult with how the integration is structured. Ill put this on the backlog for when I want a challenge.

**Comment by purcell-lab** [comment]
Wall connector device is now showing vehicle names, thanks!

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/35c4f32c-f54e-4904-ad16-5736512fc590)
