### ISSUE TITLE
Request - keep state after HA restart, or force car awake on startup to get data

### ISSUE THREAD

**Issue by jtaseff** [Teslemetry/hass-teslemetry#29]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Edit: realized this was due to an HA restart timed exactly an hour after parking the car, updating to match what actually happened.
I used to have an automation (with Tesla hacs integration that got killed by the new token requirements) - checking at 10pm that the car was plugged in. Today I happened to restart HA, and all of the states go to Unknown, thus breaking my automation until I manually woke up the car.

### Describe the solution you'd like

Can we keep the previous known state if the car doesn't have live data? Or, the other Tesla integration solved it with an option to force the car awake and update data on startup.

**Comment by jtaseff** [comment]
actually feel free to cancel this - realized I can automate on HA startup natively and call the wake button

**Comment by Bre77** [comment]
> actually feel free to cancel this - realized I can automate on HA startup natively and call the wake button

This is the way.
