### ISSUE TITLE
Additional vehicle endpoints

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#33]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I use some additional vehicle end points in my integrations.

### Describe the solution you'd like

It would be good if these could be added:

charger_phases 2
charge_current_request 2
charge_current_request_max 16
charger_actual_current 0
conn_charge_cable IEC
fast_charger_present false
fast_charger_type ACSingleWireCAN

**Comment by Bre77** [comment]
**charge_current_request** and **charge_current_request_max** are the charge current number entity.
Curious what the usecase is for the rest, but I have no problems adding them as disabled by default entities.

**Comment by purcell-lab** [comment]
current_request, current_max and current_actual have different values at different times.  Would be good as attributes of the main current sensor, but you said we aren't supporting attributes in HA core (although I note location does have kat/ long as attributes)

I use charger_phases to determine the optimal charge power to schedule;

```
    - name: p_nom_ev
      unique_id: 4e531d66-eaff-4de6-b670-e9ab3d0ed793
#      state: "{{states('sensor.ev_extremely_low_charge_rate')}}"
      state:    >-
        {% if is_state_attr('sensor.m3p_charger_power','charger_phases',2) %}
          {{240*16*3}}
        {% else -%}
          {{240*32*1}}
        {% endif %}
```

Also to determine how many hours I should schedule charging for based on a range of variables:

```

#    - name: def_total_hours_ev
#      unique_id: 7663c831-7d49-4d62-a358-d743ddd25284
#      state: "{{is_state('automation.p_deferable2_automation','on')|abs
#             * (is_state('device_tracker.m3p_location_tracker','home')|abs) 
#             * (is_state('binary_sensor.m3p_charger', 'on') | abs) 
#             * (min(state_attr('sensor.m3p_time_charge_complete','minutes_to_full_charge')/60|int(0)+1,
#                    (states('number.m3p_charge_limit')|int(0) - states('sensor.m3p_battery')|int(0))
#                    /5/state_attr('sensor.m3p_charger_power','charger_phases')|int(0)+0.9))|float(0)|round(1)}}"
#
```

**Comment by Bre77** [comment]
current_max is an attribute, this isnt hardcoded, its the API value. I'll add the actual and such as sensors.
```
min: 0
max: 32 <<<<<<
step: 1
mode: box
unit_of_measurement: A
device_class: current
```

**Comment by purcell-lab** [comment]
I don't have any attributes on my number entity.
![Screenshot_20240215-104248](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/91c4fc4e-21d4-4110-8007-b238fdbaaaeb)

**Comment by Bre77** [comment]
I think that page might only show custom attributes? Using `developer-tools/state` it shows them, so it will be avaliable for automations.

`{{ state_attr("number.sonic_charge_current_2","max") }}`

**Comment by purcell-lab** [comment]
Oh right, you have setup as the limits for the number entity.

Learnt something new today :-)
![Screenshot_20240215-110027](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/ae462cb5-3bcc-4f9c-adb0-ade87e067cb8)

**Comment by purcell-lab** [comment]
_charger_amps_actual_ & _charger_amps_request_ can be and are often different.

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/7a7f7a75-33ad-45aa-b19c-e12908331379)

**Comment by Bre77** [comment]
Charger current is **already** a entity in the sensor platform.

**Comment by Bre77** [comment]
@purcell-lab is there anything still outstanding from this issue?

**Comment by purcell-lab** [comment]
All working well, thanks.
