### ISSUE TITLE
none entities 

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#35]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration seems to create lots of entities with _none_ in the name for both vehicle and energy products.

![image](https://github.com/Teslemetry/hacs-teslemetry/assets/79175134/ae5831c9-076b-41b4-870b-932afabda53a)

**Comment by Bre77** [comment]
I've implemented a quality check, so there should be no more entities without translations. Unfortunately if you still have none entities in Home Assistant you may need to delete them or remove the integration and restart.
