### ISSUE TITLE
1.7.4: Enablement of streaming sensor entities

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#46]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Some streaming values are coming though, such as SOC:
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/4683eebc-43ca-49b3-9a81-03ba2b0b69f2)

```
data: {"data":{"Soc":"81.488","ChargeAmps":"5","ChargeEnableRequest":"true","ChargeLimitSoc":"80","ChargeState":"Idle","ChargeCurrentRequestMax":"16"},"createdAt":"2024-03-15T10:24:54.092491867Z","vin":"5YJ3F7EC5LF698201"}
```

Whilst others are remaining unknown.

![Screenshot 2024-03-15 20 47 11](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/db640be9-d6bf-42b4-b8ad-852fff45bc16)
![Screenshot 2024-03-15 20 45 33](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/74545fe9-f626-42ed-8f6c-48392803b827)

```
data: {"data":{"EnergyRemaining":"57.120"},"createdAt":"2024-03-15T10:21:23.044564992Z","vin":"5YJ3F7EC5LF698201"}
data: {"data":{"ACChargingPower":"0.000"},"createdAt":"2024-03-15T10:21:53.042763605Z","vin":"5YJ3F7EC5LF698201"}
```

**Comment by Bre77** [comment]
I currently do not know why this is the case, and it will require further investigation on my part.

**Comment by purcell-lab** [comment]
Sorry this was only a transient issue with 1.7.4 it has since been resolved.
