### ISSUE TITLE
navigation_gps_request / navigation_request REST commands

### ISSUE THREAD

**Issue by StephenBrown2** [Teslemetry/hass-teslemetry#51]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

With the tesla_custom integration, I was able to send commands via the API. The main use I had for this was for sending locations to the nav, as if shared from my phone.

This is possible to do via the Fleet API with:
https://developer.tesla.com/docs/fleet-api#navigation_request and
https://developer.tesla.com/docs/fleet-api#navigation_gps_request
endpoints.

### Describe the solution you'd like

Could we get a service to call to send location addresses (`navigation_request`) or coordinates (`navigation_gps_request`) to our vehicles?

### Additional context

This is not asking for a general `api` service, a la https://github.com/alandtse/tesla/blob/23d23d950d23fd1bfabecc4fa421965086c18451/custom_components/tesla_custom/services.py#L78-L117, but a more focused one. However, if a general service would be better, since it appears at least the `navigation_request` command must be done via the REST API: https://github.com/teslamotors/vehicle-command/blob/281db4f5fd82110bd269f933db9bbe50c20c2d89/pkg/proxy/command.go#L335-L336, then that could be useful, even if you need to disavow any liability and not include it in the HASS Core integration.

**Comment by Bre77** [comment]
Hello @StephenBrown2 

This is definitely something I want to add sooner rather than later. 

I have added it to the roadmap. https://teslemetry.canny.io/feature-requests/p/send-navigation-requests-using-a-custom-service

**Comment by StephenBrown2** [comment]
Thanks! Looking forward to it.

**Comment by Bre77** [comment]
GPS request was added to [1.7.7](https://github.com/Teslemetry/hass-teslemetry/releases/tag/v1.7.7)

Location request will be next.

**Comment by Bre77** [comment]
These have all been added, but location requests are not well documented by Tesla so its hard to know how to use it correctly. See https://teslemetry.com/docs/home-assistant/features#navigate-to-address

**Comment by fhteagle** [comment]
@Bre77 @StephenBrown2  -

I figured out the navigation request syntax, it's the same as the old Owner API:

```
curl --header 'Content-Type: application/json' \
                                                  --header "Authorization: Bearer YOURTOKENHERE" \
                                                  --data '{
                                            "type": "share_ext_content_raw",
                                            "locale": "en-US",
                                            "timestamp_ms": "1715867362999",
                             "value": {
                               "android.intent.extra.TEXT": "Cedar Rapids, IA, USA"
                               }
                                          }' \
                                                  'https://api.teslemetry.com/api/1/vehicles/YOURVINHERE/command/navigation_request'

```
