### ISSUE TITLE
HA sees sensor value as string, not float 

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [Teslemetry/hass-teslemetry#53]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have created a subscription to log `ModuleTempMax` value in Home Assistant.

unfortunately, it looks that value is returned as string and logged as string by HA, where it should be returned and saved as integer or float value.
This makes it harder or impossible to graph.

![IMG_1283](https://github.com/Teslemetry/hass-teslemetry/assets/24268470/5660cb74-c52d-488c-96bf-cd8ed3c03195)

### Reproduction steps

1. In Teslemetry console configure streaming of battery temperature
2. In Home Assistant enable sensor representing that particular measurement
3. Watch for values shown by HA

### Debug logs

```text
N/A
```

**Comment by Bre77** [comment]
This should have been fixed in v1.7.10, can you try it out and close this if its now resolved.

**Comment by KrzysztofHajdamowicz** [comment]
Unfortunately, it does not help :(

I changed definition of sensor
```Python
    TeslemetryStreamSensorEntityDescription(
        key=TelemetryField.MODULE_TEMP_MAX,
        entity_registry_enabled_default=False,
        value_fn=lambda x: float(x),
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        suggested_display_precision=1,
    ),
```

Home Assistant quickly saw this change and values render properly now.
Ergo, all streamed values need such refactor :|

**Comment by Bre77** [comment]
Should be fixed now, feel free to continue raining any entities that are coming in as strings instead of numbers.
