### ISSUE TITLE
Access DRIVER support

### ISSUE THREAD

**Issue by degrashopper** [Teslemetry/hass-teslemetry#55]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently the streaming functionality is implemented and you need OWNER access for this.
I drive a model y via a Lease contract so they are the OWNER and i only have DRIVER access with my account. Please make sure that accounts with only DRIVER access can (partialy) use this integration. After upgrading to v1.7.10 im not able to sign in.

### Describe the solution you'd like

Make sure that accounts with DRIVER access can (partialy) use this integration.

**Comment by degrashopper** [comment]
> ### Checklist
> * [x]  I have filled out the template to the best of my ability.
> * [x]  This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
> * [x]  This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
> 
> ### Is your feature request related to a problem? Please describe.
> Currently the streaming functionality is implemented and you need OWNER access for this. I drive a model y via a Lease contract so they are the OWNER and i only have DRIVER access with my account. Please make sure that accounts with only DRIVER access can (partialy) use this integration. After upgrading from v1.7.6 to v1.7.10 i get a failure error.
> 
> ### Describe the solution you'd like
> Make sure that accounts with DRIVER access can (partialy) use this integration.
> 
> ### Additional context
> _No response_

**Comment by Bre77** [comment]
Thanks for bringing this to my attension. I have tried to address this in v1.7.11. Can you give it a go and let me know if it works or not?
https://github.com/Teslemetry/hass-teslemetry/releases/tag/v1.7.11

**Comment by degrashopper** [comment]
@Bre77 updated to v1.7.11 and got the error again.

Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 12:01:08 (2 occurrences)
Last logged: 12:50:52

Error setting up entry Teslemetry for teslemetry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/__init__.py", line 138, in async_setup_entry
    remove_listeners=remove_listeners,
                     ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'remove_listeners' where it is not associated with a value

**Comment by Bre77** [comment]
Fixed in v1.7.12
