### ISSUE TITLE
UnboundLocalError prevents integration setup & loading

### ISSUE THREAD

**Issue by ghelanijimmy** [Teslemetry/hass-teslemetry#57]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This line for assining `remove_listeners` throws an UnboundLocalError: cannot access local variable 'remove_listeners' where it is not associated with a valueUnboundLocalError: cannot access local variable 'remove_listeners' where it is not associated with a value.

### Reproduction steps

1. Start Home assistant
2. Integration fails to start
3. Check logs and it throws an UnboundLocalError
4. Inside __init__.py

**Comment by Bre77** [comment]
Fixed in v1.7.12
