### ISSUE TITLE
wall connector: State and Fault state seen as string, not int

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [Teslemetry/hass-teslemetry#59]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![Screenshot 2024-03-26 at 14 08 54](https://github.com/Teslemetry/hass-teslemetry/assets/24268470/34f1069d-e927-4579-be7c-4128edd80896)

I tried to add `value_fn` in sensor.py `WALL_CONNECTOR_DESCRIPTIONS`, but `SensorEntityDescription` does not provide/expect `value_fn` fields, so Home Assistant can't initialize with such change.

**Comment by Bre77** [comment]
Can you share what values your trying to map to the codes?

**Comment by KrzysztofHajdamowicz** [comment]
> 
> Can you share what values your trying to map to the codes?

Line 33
https://github.com/home-assistant/core/blob/dev/homeassistant/components/tesla_wall_connector/sensor.py

**Comment by Bre77** [comment]
Ill take another look at it but I believe we identified that the codes do not match up between the Wall Connector API and the Fleet API

**Comment by KrzysztofHajdamowicz** [comment]
> Ill take another look at it but I believe we identified that the codes do not match up between the Wall Connector API and the Fleet API

States 2,4 and 8 matches in my case

**Comment by purcell-lab** [comment]
Looks like fault state from teslemetry 8 should be mapped to charging:

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/cd68439f-c75d-4484-92c6-ff69a5f8111c)

But that comes up as status code 11 in the Tesla Wall Connector integration:
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/f0b9fe00-c743-474a-b484-327c3aae1791)

**Comment by Bre77** [comment]
> Looks like fault state from teslemetry 8 should be mapped to charging:
> 
> But that comes up as status code 11 in the Tesla Wall Connector integration:

Fault state and state are different values, but your getting state 1 "not_connected" which is also clearly is wrong.

**Comment by purcell-lab** [comment]
Wall connector states looking good now:
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/3a05c5f3-b262-4c0e-a4e1-fafcf338e760)
![Screenshot 2024-03-30 12 10 39](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/2d17cd49-ba9e-477a-9b76-8e66619dec94)
![Screenshot 2024-03-30 12 10 19](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/2c6c97c7-debe-40c1-9eb1-c5c5020f4366)
