### ISSUE TITLE
Statistics missing from vehicle EnergyRemaining streaming entity

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#63]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I seem to be missing statistics from the EnergyRemaining sensor. 

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/25118fd0-f1ee-4643-bace-c93db764ae6e)

I can see history for this entity:

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/85135564-ffa9-47b1-a153-62122b33c0a0)

**Comment by Bre77** [comment]
Can you please check for issues at `/developer-tools/statistics`

**Comment by purcell-lab** [comment]
Ah yes, this was resolved by fixing the statistics issue.
