### ISSUE TITLE
Model details for Powerwall

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#64]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Powerwall comes up as unknown model in devices section:

![Screenshot 2024-04-02 14 19 18](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/4b0ab21e-7d4c-4286-ab04-c55472616ee2)

### Describe the solution you'd like

It would be useful to grab part_name and maybe connected batteries part names and numbers.

```json
      "gateways": [
        {
          "device_id": "28d43400-3e08-4f2f-99e0-XXX",
          "din": "1152100-14-J--XXX",
          "serial_number": "XXX",
          "part_number": "1152100-14-J",
          "part_type": 10,
          "part_name": "Tesla Backup Gateway 2",
          "is_active": true,
          "site_id": "6ceeeb74-7df9-4e37-91d1-18c7fdee2ea3",
          "firmware_version": "24.4.0 0fe780c9",
          "updated_datetime": "2024-04-01T05:54:09.531Z"
        }
      ],
      "batteries": [
        {
          "device_id": "388484da-b016-42cf-ad8e-be338f9e7882",
          "din": "3012170-05-C--YYY",
          "serial_number": "YYY",
          "part_number": "3012170-05-C",
          "part_type": 2,
          "part_name": "Powerwall 2",
          "nameplate_max_charge_power": 5000,
          "nameplate_max_discharge_power": 5000,
          "nameplate_energy": 13500
        },
        {
          "device_id": "a556aade-084f-4012-b1b3-23981a07a8b7",
          "din": "3012170-10-B--ZZZ",
          "serial_number": "ZZZ",
          "part_number": "3012170-10-B",
          "part_type": 2,
          "part_name": "Powerwall 2",
          "nameplate_max_charge_power": 5000,
          "nameplate_max_discharge_power": 5000,
          "nameplate_energy": 13500
        },
```

**Comment by Bre77** [comment]
Is this in the site_info API?
Do you have a suggestion on how to combine them? Just `Tesla Backup Gateway 2 and Powerwall 2`?

**Comment by purcell-lab** [comment]
Yes this is site_info end point.

Yes. Tesla Backup Gateway 2 and Powerwall 2 in my case.

There are some gateway/ powerwall 1 and now gateway 3 in the wild so you may see some of those as well.

**Comment by Bre77** [comment]
This has been added, will be in the next release.
