### ISSUE TITLE
Energy remaining sensor - no statistics found

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#70]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The _EnergyRemaining_ sensor (populated though streaming) doesn't maintain statistics, even though it is class _measurement_.

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/68d07ae0-165e-4218-9de2-994efb64eb5e)

By comparison and what is expected such as the _PackVoltage_ sensor.

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/ff998e94-1e48-41e9-a0b8-9152899273dd)

Or even the _EnergyAdded_ sensor.
![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/6964dfae-e8c5-4543-b64a-532c62f0ad6e)

**Comment by Bre77** [comment]
It look a few minutes, but I am getting statistics from that sensor.  Can you check your `/developer-tools/statistics`
![image](https://github.com/Teslemetry/hass-teslemetry/assets/2647914/0b434586-8fa9-4548-b65c-dddd1508b1ca)

**Comment by purcell-lab** [comment]
That was the issue, thanks.

I suspect I had originally adopted this before you included units for all elements.

![image](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/a96fa09e-190a-4818-bce0-6f15806ada59)
