### ISSUE TITLE
Call:service switch:turn_on against switch.mycar_charge while it is already on gives error

### ISSUE THREAD

**Issue by fhteagle** [Teslemetry/hass-teslemetry#77]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Manipulating the charger switch.mycar_charge works as expected in the UI. However, if the call: service switch.turn_on automation action is called while the switch is already on, the following error popup is given when manually running the automation action:

"Error running action
is_charging"

if calling the service via the developer tools screen, this is displayed at the bottom instead:

"Failed to call service switch.turn_on. is_charging"

Calling the switch.turn_on service while the switch is off proceeds as expected and without error. 

The same error/issue exists for calling switch.turn_off if switch.mycar_charge is already off.

### Reproduction steps

1. Ensure switch.mycar_charge is in the "on" position 
2. Call service switch.turn_on against switch.mycar_charge
3. Note error popup

or 

1. Ensure switch.mycar_charge is in the "off" position 
2. Call service switch.turn_off against switch.mycar_charge
3. Note error popup

### Debug logs

```text
Not seeing anything relevant in homeassistant.log, even with teslemetry custom component debugging turned on.

in System > Logger, there are these entries:


Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:797
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:49:37 (3 occurrences)
Last logged: 07:56:50

[129220410837184] is_charging
[129219800871744] is_charging
```

and 

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:1934
First occurred: 07:49:37 (3 occurrences)
Last logged: 07:56:50

websocket_api script: Error executing script. Error for call_service at pos 1: is_charging
```
```

**Comment by Bre77** [comment]
Ignoring both "not_charging" and "requested"
