### ISSUE TITLE
FR: don't force number entities UI presentation to be "box"

### ISSUE THREAD

**Issue by fhteagle** [Teslemetry/hass-teslemetry#79]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

the number.mycar_charge_limit and number.mycar_charge_current are forced by code to be presented as a digital input box by the following line :
https://github.com/Teslemetry/hass-teslemetry/blob/54b9da01b991320d1ce0ee405832735d406cf4fe/custom_components/teslemetry/number.py#L76

### Describe the solution you'd like

However, the "slider" is much easier to use in my opinion, and that option is unlocked by not forcing the input to be a box. Consider changing this line to

```mode=NumberMode.auto,```   

Which is in-line with recommended practice in HA documentation.

### Additional context

Relevant HA entity documentation:

https://developers.home-assistant.io/docs/core/entity/number/

**Comment by Bre77** [comment]
Done, will be in next release.
