### ISSUE TITLE
FR/question: Sensor for current driver profile in use?

### ISSUE THREAD

**Issue by fhteagle** [Teslemetry/hass-teslemetry#83]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Describe the solution you'd like

Is there an existing sensor for which driver profile is in currently in use? I.e. if the car has an "Alice" profile, and a "Bob" profile, can we get which one is selected at that time? Obviously controlling it would be even better (i.e. to pre-set the driver seat position before departure), but even being able to read which profile is active could help with intelligently routing notifications. I looked through the Tesla Fleet API doc and could not find this data exposed, but wondered if there is a field that is exposed but not documented?

**Comment by Bre77** [comment]
This definitely was a field in the owners API, but it would seem it's not on the Fleet API, we simply get a user present Boolean, rather than the users ID.

As such, I don't think this is possible anymore.

**Comment by fhteagle** [comment]
Yeah it looks like Tesla forgot this when implementing the Fleet API. Boo. 

I'll mark it "Won't Fix" for now, but hopefully they add that back in the future...
