### ISSUE TITLE
New (calculated) Sensor: BrickVoltageDelta

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [Teslemetry/hass-teslemetry#90]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It's possible to stream fields BrickVoltageMin and BrickVoltageMax directly to HA using this integration.
Creating new template sensor to substract one from another creates entity that is outside of "device" section in integrations overview.

Exposing calculated BrickVoltageDelta by integration solves observability issue while makes it visible in 'Devices' section along other sensors

### Describe the solution you'd like

Create new sensor, BrickVoltageDelta that substracts BrickVoltageMin from BrickVoltageMax.
When those fields are not streamed, set state Unknown and add attribute `Reason: both BrickVoltageMin, BrickVoltageMax have to be streaming using Fleet Telemetry` or something like that

**Comment by Bre77** [comment]
Its also fairly easy to set this up yourself with a helper entity.

![image](https://github.com/Teslemetry/hass-teslemetry/assets/2647914/b3dfbf82-f43a-48b3-9d6c-95c66211bb30)

Create a `Combine the state of several sensors` helper, select `Statistical ranage`, then the two battery voltage sensors.

The Home Assistant project has rules against this sort of calculated sensor being in the integrations themselves, given the helper system exists.
